### PR TITLE
Updates for JWS 5.6.0

### PR DESCRIPTION
**Pull request by mdrafiur**

### CODE REVIEW

**Comment by bekionel** [comment]
@mdrafiur I see that with this PR you've completely removed the imagestream and templates. Was that intentional or a mistake? Apart from that, it looks good to me.

**Comment by mdrafiur** [comment]
@bekionel I noticed the templates directory has been removed from the x86 branch (webserver56-dev-rhel8). Can you please confirm if the templates should be there and I can add it back.

**Comment by bekionel** [comment]
@mdrafiur yes, please add them back as they had been removed by mistake. I just realised I hadn't pushed the fix here but only on my fork; I've just updated this repo as well (branch webserver56-dev-rhel8). [commit](https://github.com/jboss-container-images/jboss-webserver-5-openshift-image/commit/dc18846ba20a84a7387f66b71864f1ec938f3e91)

**Comment by mdrafiur** [comment]
@bekionel The templates files are added back and updated for the 5.6. Please review and let me know if any other fix is required.

**Comment by bekionel** [comment]
@mdrafiur You need to remove the JWS_ADMIN_USERNAME and JWS_ADMIN_PASSWORD from the templates, see dc18846ba20a84a7387f66b71864f1ec938f3e91 . The jira for reference is https://issues.redhat.com/browse/JWS-2051

**Comment by mdrafiur** [comment]
Hi @bekionel, The JWS_ADMIN_USERNAME and JWS_ADMIN_PASSWORD have been removed from the templates.

Also, QE identified test failures and adding back the 'os-jws-rm-root' module resolved the issue. Please review and let me know if any other change is required. Thanks

**Comment by bekionel** [comment]
@mdrafiur Can you please squash the last 5 commits into a single one to avoid the extra noise in history?

**Comment by mdrafiur** [comment]
@bekionel Squashed the last 5 commits

**Comment by bekionel** [comment]
Thanks, merging.

**Pull request merged**
